repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  - repo: git@github.com:psf/black.git
    rev: 24.4.2
    hooks:
      - id: black

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-length']
